/* This file was generated by SableCC (http://www.sablecc.org/). */

package dk.aau.cs.d402f13.ScannerParser.node;

import dk.aau.cs.d402f13.ScannerParser.analysis.*;

@SuppressWarnings("nls")
public final class ALambdaExpression extends PExpression
{
    private PLambdaExpr _lambdaExpr_;

    public ALambdaExpression()
    {
        // Constructor
    }

    public ALambdaExpression(
        @SuppressWarnings("hiding") PLambdaExpr _lambdaExpr_)
    {
        // Constructor
        setLambdaExpr(_lambdaExpr_);

    }

    @Override
    public Object clone()
    {
        return new ALambdaExpression(
            cloneNode(this._lambdaExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALambdaExpression(this);
    }

    public PLambdaExpr getLambdaExpr()
    {
        return this._lambdaExpr_;
    }

    public void setLambdaExpr(PLambdaExpr node)
    {
        if(this._lambdaExpr_ != null)
        {
            this._lambdaExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lambdaExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lambdaExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lambdaExpr_ == child)
        {
            this._lambdaExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lambdaExpr_ == oldChild)
        {
            setLambdaExpr((PLambdaExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
