/* This file was generated by SableCC (http://www.sablecc.org/). */

package dk.aau.cs.d402f13.ScannerParser.lexer;

import java.io.*;
import dk.aau.cs.d402f13.ScannerParser.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEol(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBlank(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDecimal(text, line, pos); }
    Token new3(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLowercase(text, line, pos); }
    Token new4(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TUppercase(text, line, pos); }
    Token new5(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TUnichar(text, line, pos); }
    Token new6(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStrchar(text, line, pos); }
    Token new7(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKeyword(text, line, pos); }
    Token new8(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOperator(text, line, pos); }
    Token new9(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPatternKeyword(text, line, pos); }
    Token new10(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPatternOperator(text, line, pos); }
    Token new11(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDirection(text, line, pos); }
    Token new12(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStarQmarkPlus(text, line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDefine(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGame(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBkt(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBkt(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBrc(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBrc(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLPar(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRPar(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNot(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIf(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TThen(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TElse(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPound(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TArrow(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSlash(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStar(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TQMark(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPlus(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEmark(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFriend(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFoe(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEmpty(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TThis(line, pos); }
    Token new36(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInteger(text, line, pos); }
    Token new37(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCoordinate(text, line, pos); }
    Token new38(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TString(text, line, pos); }
    Token new39(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFunction(text, line, pos); }
    Token new40(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentifier(text, line, pos); }
    Token new41(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVariable(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{0, 8, 1}, {9, 9, 2}, {10, 10, 3}, {11, 12, 1}, {13, 13, 4}, {14, 31, 1}, {32, 32, 5}, {33, 33, 6}, {34, 34, 7}, {35, 35, 8}, {36, 36, 9}, {37, 39, 1}, {40, 40, 10}, {41, 41, 11}, {42, 42, 12}, {43, 43, 13}, {44, 46, 1}, {47, 47, 14}, {48, 57, 15}, {58, 60, 1}, {61, 61, 16}, {62, 62, 1}, {63, 63, 17}, {64, 64, 1}, {65, 90, 18}, {91, 91, 19}, {92, 92, 20}, {93, 93, 21}, {94, 96, 1}, {97, 97, 22}, {98, 98, 23}, {99, 99, 24}, {100, 100, 25}, {101, 101, 26}, {102, 102, 27}, {103, 103, 28}, {104, 104, 29}, {105, 105, 30}, {106, 109, 24}, {110, 110, 31}, {111, 111, 32}, {112, 112, 33}, {113, 114, 24}, {115, 115, 34}, {116, 116, 35}, {117, 118, 24}, {119, 119, 36}, {120, 122, 24}, {123, 123, 37}, {124, 124, 1}, {125, 125, 38}, {126, 65535, 1}, },
            {},
            {},
            {},
            {{10, 10, 39}, },
            {},
            {},
            {{0, 33, 40}, {34, 34, 41}, {35, 91, 40}, {92, 92, 42}, {93, 65535, 40}, },
            {},
            {{65, 90, 43}, {97, 122, 44}, },
            {},
            {},
            {},
            {},
            {},
            {{48, 57, 45}, },
            {{62, 62, 46}, },
            {},
            {{48, 57, 47}, {65, 90, 48}, {97, 122, 49}, },
            {},
            {},
            {},
            {{65, 90, 50}, {97, 109, 51}, {110, 110, 52}, {111, 122, 51}, },
            {{65, 90, 50}, {97, 110, 51}, {111, 111, 53}, {112, 122, 51}, },
            {{65, 90, 50}, {97, 122, 51}, },
            {{65, 90, 50}, {97, 100, 51}, {101, 101, 54}, {102, 122, 51}, },
            {{65, 90, 50}, {97, 107, 51}, {108, 108, 55}, {109, 109, 56}, {110, 122, 51}, },
            {{65, 110, -25}, {111, 111, 57}, {112, 113, 51}, {114, 114, 58}, {115, 122, 51}, },
            {{65, 90, 50}, {97, 97, 59}, {98, 113, 51}, {114, 114, 60}, {115, 122, 51}, },
            {{65, 100, -27}, {101, 101, 61}, {102, 122, 51}, },
            {{65, 90, 50}, {97, 101, 51}, {102, 102, 62}, {103, 122, 51}, },
            {{65, 90, 50}, {97, 97, 63}, {98, 100, 51}, {101, 101, 64}, {102, 110, 51}, {111, 111, 65}, {112, 118, 51}, {119, 119, 66}, {120, 122, 51}, },
            {{65, 90, 50}, {97, 113, 51}, {114, 114, 67}, {115, 122, 51}, },
            {{65, 90, 50}, {97, 104, 51}, {105, 105, 68}, {106, 107, 51}, {108, 108, 69}, {109, 110, 51}, {111, 111, 70}, {112, 122, 51}, },
            {{65, 100, -27}, {101, 101, 71}, {102, 118, 51}, {119, 119, 72}, {120, 122, 51}, },
            {{65, 90, 50}, {97, 103, 51}, {104, 104, 73}, {105, 105, 74}, {106, 116, 51}, {117, 117, 75}, {118, 122, 51}, },
            {{65, 90, 50}, {97, 97, 76}, {98, 104, 51}, {105, 105, 77}, {106, 122, 51}, },
            {},
            {},
            {},
            {{0, 65535, -9}, },
            {},
            {{0, 65535, 78}, },
            {{65, 122, -11}, },
            {{65, 122, -11}, },
            {{48, 57, 45}, },
            {},
            {{48, 57, 47}, },
            {{48, 122, -20}, },
            {{65, 90, 79}, {97, 122, 49}, },
            {{65, 122, -26}, },
            {{65, 122, -26}, },
            {{65, 90, 50}, {97, 99, 51}, {100, 100, 80}, {101, 122, 51}, },
            {{65, 90, 50}, {97, 97, 81}, {98, 122, 51}, },
            {{65, 101, -32}, {102, 102, 82}, {103, 122, 51}, },
            {{65, 90, 50}, {97, 114, 51}, {115, 115, 83}, {116, 122, 51}, },
            {{65, 90, 50}, {97, 111, 51}, {112, 112, 84}, {113, 122, 51}, },
            {{65, 100, -27}, {101, 101, 85}, {102, 122, 51}, },
            {{65, 104, -35}, {105, 105, 86}, {106, 122, 51}, },
            {{65, 90, 50}, {97, 108, 51}, {109, 109, 87}, {110, 122, 51}, },
            {{65, 104, -35}, {105, 105, 88}, {106, 122, 51}, },
            {{65, 104, -35}, {105, 105, 89}, {106, 122, 51}, },
            {{65, 122, -26}, },
            {{65, 108, -61}, {109, 109, 90}, {110, 122, 51}, },
            {{65, 122, -26}, },
            {{65, 90, 50}, {97, 115, 51}, {116, 116, 91}, {117, 122, 51}, },
            {{65, 122, -26}, },
            {{65, 122, -26}, },
            {{65, 100, -27}, {101, 101, 92}, {102, 122, 51}, },
            {{65, 90, 50}, {97, 97, 93}, {98, 122, 51}, },
            {{65, 114, -57}, {115, 115, 94}, {116, 122, 51}, },
            {{65, 115, -67}, {116, 116, 95}, {117, 122, 51}, },
            {{65, 122, -26}, },
            {{65, 100, -27}, {101, 101, 96}, {102, 104, 51}, {105, 105, 97}, {106, 122, 51}, },
            {{65, 100, -27}, {101, 101, 98}, {102, 115, 51}, {116, 116, 99}, {117, 122, 51}, },
            {{65, 113, -34}, {114, 114, 100}, {115, 122, 51}, },
            {{65, 107, -28}, {108, 108, 101}, {109, 122, 51}, },
            {{65, 99, -54}, {100, 100, 102}, {101, 109, 51}, {110, 110, 103}, {111, 122, 51}, },
            {{0, 65535, -9}, },
            {{65, 122, -51}, },
            {{65, 122, -26}, },
            {{65, 113, -34}, {114, 114, 104}, {115, 122, 51}, },
            {{65, 104, -35}, {105, 105, 105}, {106, 122, 51}, },
            {{65, 100, -27}, {101, 101, 106}, {102, 122, 51}, },
            {{65, 115, -67}, {116, 116, 107}, {117, 122, 51}, },
            {{65, 122, -26}, },
            {{65, 100, -27}, {101, 101, 108}, {102, 122, 51}, },
            {{65, 100, -27}, {101, 101, 109}, {102, 122, 51}, },
            {{65, 99, -54}, {100, 100, 110}, {101, 122, 51}, },
            {{65, 90, 50}, {97, 102, 51}, {103, 103, 111}, {104, 122, 51}, },
            {{65, 100, -27}, {101, 101, 112}, {102, 122, 51}, },
            {{65, 122, -26}, },
            {{65, 90, 50}, {97, 98, 51}, {99, 99, 113}, {100, 122, 51}, },
            {{65, 90, 50}, {97, 120, 51}, {121, 121, 114}, {122, 122, 51}, },
            {{65, 114, -57}, {115, 115, 115}, {116, 122, 51}, },
            {{65, 90, 50}, {97, 116, 51}, {117, 117, 116}, {118, 122, 51}, },
            {{65, 109, -24}, {110, 110, 117}, {111, 122, 51}, },
            {{65, 114, -57}, {115, 115, 118}, {116, 122, 51}, },
            {{65, 66, 50}, {67, 67, 119}, {68, 90, 50}, {97, 122, 51}, },
            {{65, 107, -28}, {108, 108, 120}, {109, 122, 51}, },
            {{65, 109, -24}, {110, 110, 121}, {111, 122, 51}, },
            {{65, 107, -28}, {108, 108, 122}, {109, 122, 51}, },
            {{65, 115, -67}, {116, 116, 123}, {117, 122, 51}, },
            {{65, 66, 50}, {67, 67, 124}, {68, 122, -100}, },
            {{65, 99, -54}, {100, 100, 125}, {101, 122, 51}, },
            {{65, 109, -24}, {110, 110, 126}, {111, 122, 51}, },
            {{65, 122, -26}, },
            {{65, 120, -95}, {121, 121, 127}, {122, 122, 51}, },
            {{65, 109, -24}, {110, 110, 128}, {111, 122, 51}, },
            {{65, 122, -26}, },
            {{65, 122, -26}, },
            {{65, 103, -37}, {104, 104, 129}, {105, 122, 51}, },
            {{65, 122, -26}, },
            {{65, 100, -27}, {101, 101, 130}, {102, 122, 51}, },
            {{65, 100, -27}, {101, 101, 131}, {102, 122, 51}, },
            {{65, 104, -35}, {105, 105, 132}, {106, 122, 51}, },
            {{65, 111, -58}, {112, 112, 133}, {113, 122, 51}, },
            {{65, 122, -26}, },
            {{65, 122, -26}, },
            {{65, 110, -25}, {111, 111, 134}, {112, 122, 51}, },
            {{65, 100, -27}, {101, 101, 135}, {102, 122, 51}, },
            {{65, 78, 50}, {79, 79, 136}, {80, 90, 50}, {97, 122, 51}, },
            {{65, 122, -26}, },
            {{65, 103, -37}, {104, 104, 137}, {105, 122, 51}, },
            {{65, 110, -25}, {111, 111, 138}, {112, 122, 51}, },
            {{65, 122, -26}, },
            {{65, 100, -27}, {101, 101, 139}, {102, 122, 51}, },
            {{65, 122, -26}, },
            {{65, 99, -54}, {100, 100, 140}, {101, 122, 51}, },
            {{65, 115, -67}, {116, 116, 141}, {117, 122, 51}, },
            {{65, 122, -26}, },
            {{65, 113, -34}, {114, 114, 142}, {115, 122, 51}, },
            {{65, 90, 50}, {97, 97, 51}, {98, 98, 143}, {99, 122, 51}, },
            {{65, 122, -26}, },
            {{65, 109, -24}, {110, 110, 144}, {111, 122, 51}, },
            {{65, 122, -26}, },
            {{65, 113, -34}, {114, 114, 145}, {115, 122, 51}, },
            {{65, 122, -26}, },
            {{65, 109, -24}, {110, 110, 146}, {111, 122, 51}, },
            {{65, 122, -26}, },
            {{65, 122, -26}, },
            {{65, 122, -26}, },
            {{65, 114, -57}, {115, 115, 147}, {116, 122, 51}, },
            {{65, 107, -28}, {108, 108, 148}, {109, 122, 51}, },
            {{65, 99, -54}, {100, 100, 149}, {101, 122, 51}, },
            {{65, 99, -54}, {100, 100, 150}, {101, 122, 51}, },
            {{65, 99, -54}, {100, 100, 151}, {101, 122, 51}, },
            {{65, 122, -26}, },
            {{65, 100, -27}, {101, 101, 152}, {102, 122, 51}, },
            {{65, 104, -35}, {105, 105, 153}, {106, 122, 51}, },
            {{65, 100, -27}, {101, 101, 154}, {102, 122, 51}, },
            {{65, 104, -35}, {105, 105, 155}, {106, 122, 51}, },
            {{65, 67, 50}, {68, 68, 156}, {69, 76, 50}, {77, 77, 157}, {78, 90, 50}, {97, 122, 51}, },
            {{65, 115, -67}, {116, 116, 158}, {117, 122, 51}, },
            {{65, 113, -34}, {114, 114, 159}, {115, 122, 51}, },
            {{65, 115, -67}, {116, 116, 160}, {117, 122, 51}, },
            {{65, 113, -34}, {114, 114, 161}, {115, 122, 51}, },
            {{65, 110, -25}, {111, 111, 162}, {112, 122, 51}, },
            {{65, 104, -35}, {105, 105, 163}, {106, 122, 51}, },
            {{65, 122, -26}, },
            {{65, 104, -35}, {105, 105, 164}, {106, 122, 51}, },
            {{65, 110, -25}, {111, 111, 165}, {112, 122, 51}, },
            {{65, 90, 50}, {97, 117, 51}, {118, 118, 166}, {119, 122, 51}, },
            {{65, 110, -25}, {111, 111, 167}, {112, 122, 51}, },
            {{65, 110, -25}, {111, 111, 168}, {112, 122, 51}, },
            {{65, 111, -58}, {112, 112, 169}, {113, 122, 51}, },
            {{65, 100, -27}, {101, 101, 170}, {102, 122, 51}, },
            {{65, 109, -24}, {110, 110, 171}, {111, 122, 51}, },
            {{65, 109, -24}, {110, 110, 172}, {111, 122, 51}, },
            {{65, 114, -57}, {115, 115, 173}, {116, 122, 51}, },
            {{65, 114, -57}, {115, 115, 174}, {116, 122, 51}, },
            {{65, 122, -26}, },
            {{65, 122, -26}, },
            {{65, 122, -26}, },
            {{65, 122, -26}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 5, 1, 0, 0, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 4, 5, 5, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 0, -1, 38, -1, 41, 41, 36, 26, 37, 40, 40, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 22, 39, 11, 39, 11, 8, 39, 39, 39, 11, 11, 39, 39, 39, 39, 39, -1, 40, 8, 39, 39, 39, 39, 9, 39, 39, 39, 39, 39, 8, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 24, 39, 39, 7, 7, 39, 7, 39, 39, 39, 39, 23, 7, 39, 39, 39, 7, 39, 39, 7, 39, 9, 39, 39, 7, 39, 39, 7, 39, 7, 39, 7, 39, 13, 9, 7, 39, 39, 39, 39, 39, 7, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 7, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 7, 7, 7, 7, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
