/* This file was generated by SableCC (http://www.sablecc.org/). */

package ScannerParser.node;

import ScannerParser.analysis.*;

@SuppressWarnings("nls")
public final class ACorElement extends PElement
{
    private TCoordinate _coordinate_;

    public ACorElement()
    {
        // Constructor
    }

    public ACorElement(
        @SuppressWarnings("hiding") TCoordinate _coordinate_)
    {
        // Constructor
        setCoordinate(_coordinate_);

    }

    @Override
    public Object clone()
    {
        return new ACorElement(
            cloneNode(this._coordinate_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACorElement(this);
    }

    public TCoordinate getCoordinate()
    {
        return this._coordinate_;
    }

    public void setCoordinate(TCoordinate node)
    {
        if(this._coordinate_ != null)
        {
            this._coordinate_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._coordinate_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._coordinate_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._coordinate_ == child)
        {
            this._coordinate_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._coordinate_ == oldChild)
        {
            setCoordinate((TCoordinate) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
