/* This file was generated by SableCC (http://www.sablecc.org/). */

package ScannerParser.node;

import ScannerParser.analysis.*;

@SuppressWarnings("nls")
public final class ADeclstrucStructure extends PStructure
{
    private PDeclStruct _declStruct_;

    public ADeclstrucStructure()
    {
        // Constructor
    }

    public ADeclstrucStructure(
        @SuppressWarnings("hiding") PDeclStruct _declStruct_)
    {
        // Constructor
        setDeclStruct(_declStruct_);

    }

    @Override
    public Object clone()
    {
        return new ADeclstrucStructure(
            cloneNode(this._declStruct_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclstrucStructure(this);
    }

    public PDeclStruct getDeclStruct()
    {
        return this._declStruct_;
    }

    public void setDeclStruct(PDeclStruct node)
    {
        if(this._declStruct_ != null)
        {
            this._declStruct_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declStruct_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declStruct_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declStruct_ == child)
        {
            this._declStruct_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declStruct_ == oldChild)
        {
            setDeclStruct((PDeclStruct) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
