/* This file was generated by SableCC (http://www.sablecc.org/). */

package ScannerParser.node;

import ScannerParser.analysis.*;

@SuppressWarnings("nls")
public final class AKeyElement extends PElement
{
    private TKeyword _keyword_;

    public AKeyElement()
    {
        // Constructor
    }

    public AKeyElement(
        @SuppressWarnings("hiding") TKeyword _keyword_)
    {
        // Constructor
        setKeyword(_keyword_);

    }

    @Override
    public Object clone()
    {
        return new AKeyElement(
            cloneNode(this._keyword_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAKeyElement(this);
    }

    public TKeyword getKeyword()
    {
        return this._keyword_;
    }

    public void setKeyword(TKeyword node)
    {
        if(this._keyword_ != null)
        {
            this._keyword_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._keyword_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._keyword_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._keyword_ == child)
        {
            this._keyword_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._keyword_ == oldChild)
        {
            setKeyword((TKeyword) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
