/* This file was generated by SableCC (http://www.sablecc.org/). */

package ScannerParser.node;

import java.util.*;
import ScannerParser.analysis.*;

@SuppressWarnings("nls")
public final class AProgram extends PProgram
{
    private final LinkedList<PFunctionDef> _functionDef_ = new LinkedList<PFunctionDef>();
    private PGameDecl _gameDecl_;

    public AProgram()
    {
        // Constructor
    }

    public AProgram(
        @SuppressWarnings("hiding") List<?> _functionDef_,
        @SuppressWarnings("hiding") PGameDecl _gameDecl_)
    {
        // Constructor
        setFunctionDef(_functionDef_);

        setGameDecl(_gameDecl_);

    }

    @Override
    public Object clone()
    {
        return new AProgram(
            cloneList(this._functionDef_),
            cloneNode(this._gameDecl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgram(this);
    }

    public LinkedList<PFunctionDef> getFunctionDef()
    {
        return this._functionDef_;
    }

    public void setFunctionDef(List<?> list)
    {
        for(PFunctionDef e : this._functionDef_)
        {
            e.parent(null);
        }
        this._functionDef_.clear();

        for(Object obj_e : list)
        {
            PFunctionDef e = (PFunctionDef) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._functionDef_.add(e);
        }
    }

    public PGameDecl getGameDecl()
    {
        return this._gameDecl_;
    }

    public void setGameDecl(PGameDecl node)
    {
        if(this._gameDecl_ != null)
        {
            this._gameDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._gameDecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._functionDef_)
            + toString(this._gameDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._functionDef_.remove(child))
        {
            return;
        }

        if(this._gameDecl_ == child)
        {
            this._gameDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PFunctionDef> i = this._functionDef_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PFunctionDef) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._gameDecl_ == oldChild)
        {
            setGameDecl((PGameDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
