/* This file was generated by SableCC (http://www.sablecc.org/). */

package dk.aau.cs.d402f13.ScannerParser.node;

import dk.aau.cs.d402f13.ScannerParser.analysis.*;

@SuppressWarnings("nls")
public final class AGameDecl extends PGameDecl
{
    private TGame _game_;
    private PDeclStruct _declStruct_;

    public AGameDecl()
    {
        // Constructor
    }

    public AGameDecl(
        @SuppressWarnings("hiding") TGame _game_,
        @SuppressWarnings("hiding") PDeclStruct _declStruct_)
    {
        // Constructor
        setGame(_game_);

        setDeclStruct(_declStruct_);

    }

    @Override
    public Object clone()
    {
        return new AGameDecl(
            cloneNode(this._game_),
            cloneNode(this._declStruct_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGameDecl(this);
    }

    public TGame getGame()
    {
        return this._game_;
    }

    public void setGame(TGame node)
    {
        if(this._game_ != null)
        {
            this._game_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._game_ = node;
    }

    public PDeclStruct getDeclStruct()
    {
        return this._declStruct_;
    }

    public void setDeclStruct(PDeclStruct node)
    {
        if(this._declStruct_ != null)
        {
            this._declStruct_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declStruct_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._game_)
            + toString(this._declStruct_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._game_ == child)
        {
            this._game_ = null;
            return;
        }

        if(this._declStruct_ == child)
        {
            this._declStruct_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._game_ == oldChild)
        {
            setGame((TGame) newChild);
            return;
        }

        if(this._declStruct_ == oldChild)
        {
            setDeclStruct((PDeclStruct) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
