/* This file was generated by SableCC (http://www.sablecc.org/). */

package dk.aau.cs.d402f13.ScannerParser.node;

import dk.aau.cs.d402f13.ScannerParser.analysis.*;

@SuppressWarnings("nls")
public final class APatvalexprPatternExpr extends PPatternExpr
{
    private PPatternVal _patternVal_;
    private TPatternOr _patternOr_;
    private PPatternExpr _patternExpr_;

    public APatvalexprPatternExpr()
    {
        // Constructor
    }

    public APatvalexprPatternExpr(
        @SuppressWarnings("hiding") PPatternVal _patternVal_,
        @SuppressWarnings("hiding") TPatternOr _patternOr_,
        @SuppressWarnings("hiding") PPatternExpr _patternExpr_)
    {
        // Constructor
        setPatternVal(_patternVal_);

        setPatternOr(_patternOr_);

        setPatternExpr(_patternExpr_);

    }

    @Override
    public Object clone()
    {
        return new APatvalexprPatternExpr(
            cloneNode(this._patternVal_),
            cloneNode(this._patternOr_),
            cloneNode(this._patternExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPatvalexprPatternExpr(this);
    }

    public PPatternVal getPatternVal()
    {
        return this._patternVal_;
    }

    public void setPatternVal(PPatternVal node)
    {
        if(this._patternVal_ != null)
        {
            this._patternVal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._patternVal_ = node;
    }

    public TPatternOr getPatternOr()
    {
        return this._patternOr_;
    }

    public void setPatternOr(TPatternOr node)
    {
        if(this._patternOr_ != null)
        {
            this._patternOr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._patternOr_ = node;
    }

    public PPatternExpr getPatternExpr()
    {
        return this._patternExpr_;
    }

    public void setPatternExpr(PPatternExpr node)
    {
        if(this._patternExpr_ != null)
        {
            this._patternExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._patternExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._patternVal_)
            + toString(this._patternOr_)
            + toString(this._patternExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._patternVal_ == child)
        {
            this._patternVal_ = null;
            return;
        }

        if(this._patternOr_ == child)
        {
            this._patternOr_ = null;
            return;
        }

        if(this._patternExpr_ == child)
        {
            this._patternExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._patternVal_ == oldChild)
        {
            setPatternVal((PPatternVal) newChild);
            return;
        }

        if(this._patternOr_ == oldChild)
        {
            setPatternOr((TPatternOr) newChild);
            return;
        }

        if(this._patternExpr_ == oldChild)
        {
            setPatternExpr((PPatternExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
