/* This file was generated by SableCC (http://www.sablecc.org/). */

package dk.aau.cs.d402f13.ScannerParser.node;

import dk.aau.cs.d402f13.ScannerParser.analysis.*;

@SuppressWarnings("nls")
public final class ASharedOpOperator extends POperator
{
    private PSharedOperator _sharedOperator_;

    public ASharedOpOperator()
    {
        // Constructor
    }

    public ASharedOpOperator(
        @SuppressWarnings("hiding") PSharedOperator _sharedOperator_)
    {
        // Constructor
        setSharedOperator(_sharedOperator_);

    }

    @Override
    public Object clone()
    {
        return new ASharedOpOperator(
            cloneNode(this._sharedOperator_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASharedOpOperator(this);
    }

    public PSharedOperator getSharedOperator()
    {
        return this._sharedOperator_;
    }

    public void setSharedOperator(PSharedOperator node)
    {
        if(this._sharedOperator_ != null)
        {
            this._sharedOperator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sharedOperator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sharedOperator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sharedOperator_ == child)
        {
            this._sharedOperator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sharedOperator_ == oldChild)
        {
            setSharedOperator((PSharedOperator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
